name: Jupyter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v3

      - name: Setup Python
      - uses: actions/setup-python@v4.0.0
        with:
          cache: pip
          python-version: '3.7'

      - name: Install Dependencies
        run: pip install -r requirements.txt
        
      - name: Execute Notebook
        run: jupyter-nbconvert --execute Ridge-regression.ipynb --to html

      - name: Upload a Build Artifact
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: Artifact
          path: Ridge-regression.html
